//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsunaCan.XmlDocumentationTranslator.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsunaCan.XmlDocumentationTranslator.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Directory {directory} was created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryCreated {
            get {
                return ResourceManager.GetString("DirectoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to convert object to XML. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnableToConvertObjectToXml {
            get {
                return ResourceManager.GetString("UnableToConvertObjectToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Xml document {OutputFileName} was created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlDocumentCreated {
            get {
                return ResourceManager.GetString("XmlDocumentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{XmlDocumentPath}&apos; file was loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlDocumentLoaded {
            get {
                return ResourceManager.GetString("XmlDocumentLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading &apos;{XmlDocumentPath}&apos; file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlDocumentLoading {
            get {
                return ResourceManager.GetString("XmlDocumentLoading", resourceCulture);
            }
        }
    }
}
